server:
  port: 5102

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb
    username: root
    password: pass@word1
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT-SERVICE